FROM --platform=linux/amd64 ewfd-data-base:latest

USER root
SHELL ["/bin/bash", "-c"]

WORKDIR /work
COPY Tor-eBPF Tor-eBPF

RUN cd Tor-eBPF && source conf.sh && bash tor-tools/build/build_dynamic.sh

CMD ["/bin/bash"]