FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:jammy

USER root

COPY sources.list /etc/apt/sources.list

RUN apt-get update && apt install -y software-properties-common 
RUN apt install -y clangd bear automake libevent-dev git

WORKDIR /workspaces
RUN git clone https://oauth2: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@github.com/IoTAccessControl/Tor-eBPF.git
CMD ["/bin/sh"]